### ISSUE TITLE
[Report] mono 7.1.1 -> 7.3.0

### ISSUE THREAD

**Issue by X9VoiD** [bottlesdevs/dependencies#106]
**Which dependency?**
`mono`

**Problem type**
Outdated

**Describe the problem**
There is a new update to wine-mono. As of 8b1dd7f16e1056b9eafe5c98a7d06d004455d98e, the manifest is
```
Name: mono
Description: Wine mono
Provider: WineHQ
License: WineHQ
License_url: https://wiki.winehq.org/Mono
Dependencies: []
Steps:
- action: uninstall
  file_name: Wine Mono
  
- action: install_msi
  file_name: wine-mono-7.1.1-x86.msi
  url: https://dl.winehq.org/wine/wine-mono/7.1.1/wine-mono-7.1.1-x86.msi
  rename: wine-mono-7.1.1-x86.msi
  file_checksum: 7585cffd0ac8a4ed9558697471208591
  file_size: 86606336
```
However, there is a new release: https://dl.winehq.org/wine/wine-mono/7.3.0/wine-mono-7.3.0-x86.msi
