### ISSUE TITLE
[Request dependency]

### ISSUE THREAD

**Issue by mariohevia** [bottlesdevs/dependencies#107]
**Dependency name**: MFC71.DLL

**Official link to the download page (not direct download)** https://www.microsoft.com/en-us/download/details.aspx?id=21440

**Is this dependency compatible with Wine?**
- [ ] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ X ] I have not tested

**Useful links**

Explains what MFC71.DLL isL
https://www.lifewire.com/how-to-fix-mfc71-dll-not-found-or-missing-errors-2623641

They can be links to guides for its implementation or testing or other. Each reference can be useful to maintainers to implement the dependency.

**Comment by keenanweaver** [comment]
Manifests based on the [Winetricks method](https://github.com/Winetricks/winetricks/blob/d5bc8a08fe6ed338e4d8d9490d425f1dbea137db/src/winetricks#L12531). Unfortunately, neither `archive_extract` nor `cab_extract` supports the file format. Unless there's another file that contains these DLLs, a new function will need to be created. Winetricks uses a 7zip function, apparently: https://github.com/Winetricks/winetricks/blob/d5bc8a08fe6ed338e4d8d9490d425f1dbea137db/src/winetricks#L644

``` yml
Name: mfc71
Description: Visual C++ 2003 mfc71 library; part of vcrun2003
Provider: Microsoft
License:
License_url:
Dependencies: []
Steps:
- action: archive_extract
  file_name: BZEditW32_1.6.5.exe
  url: https://sourceforge.net/projects/bzflag/files/bzedit%20win32/1.6.5/BZEditW32_1.6.5.exe
  file_checksum: 15c3d0a4acaae1c3013242bca43a5a86

- action: copy_dll
  url: BZEditW32_1.6.5.exe/
  file_name: mfc71.dll
  dest: win32
```

``` yml
Name: vcrun2003
Description: Visual C++ 2003 libraries (mfc71,msvcp71,msvcr71)
Provider: Microsoft
License:
License_url:
Dependencies:
  - mfc71
Steps:
- action: archive_extract
  file_name: BZEditW32_1.6.5.exe
  url: https://sourceforge.net/projects/bzflag/files/bzedit%20win32/1.6.5/BZEditW32_1.6.5.exe
  file_checksum: 15c3d0a4acaae1c3013242bca43a5a86

- action: copy_dll
  url: temp/BZEditW32_1.6.5.exe/
  file_name: msvcp71.dll
  dest: win32

- action: copy_dll
  url: temp/BZEditW32_1.6.5.exe/
  file_name: msvcr71.dll
  dest: win32
```

**Comment by mirkobrombin** [comment]
p7zip is a Bottles dependency and archive_extract uses it to extract 7z archives (example [here](https://github.com/bottlesdevs/dependencies/blob/f0dddb10f66a6ac34a2349e9eed6af7910575fd0/Essentials/d3dcompiler_47.yml))

**Comment by keenanweaver** [comment]
Seems to hang when using archive_extract in this manner:
```yaml
- action: archive_extract
  file_name: BZEditW32_1.6.5.exe
  url: https://sourceforge.net/projects/bzflag/files/bzedit%20win32/1.6.5/BZEditW32_1.6.5.exe
  file_checksum: 15c3d0a4acaae1c3013242bca43a5a86
```


```
12:22:09 (INFO) Installing dependency [mfc71] in bottle [Test]. 
BZEditW32_1.6.5.exe (100%) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (862.0KiB/861.6KiB - 700.8KiB)

patool: Extracting /home/keenan/.var/app/com.usebottles.bottles/data/bottles/temp/BZEditW32_1.6.5.exe ...
```
![bzedit](https://user-images.githubusercontent.com/37268985/190223180-7b8f7d74-7cd4-4ae2-b4e7-9bc6e5b8b53e.png)

Downloading p7zip and running it manually, seemingly extracts fine with the command `7z x BZEditW32_1.6.5.exe -o/home/keenan/.var/app/com.usebottles.bottles/data/bottles/temp/BZEditW32_1.6.5_manual`

![bzedit2](https://user-images.githubusercontent.com/37268985/190225795-860ebb13-f642-4a54-8349-98673a043406.png)
