### ISSUE TITLE
[Report] vcredist2012 doesn't install

### ISSUE THREAD

**Issue by Bananaman** [bottlesdevs/dependencies#11]
**Which dependency?**
vcredist2012

**Problem type**
- trying to install it just shows a "!" exclamation mark in the Bottles GUI
- failed to install (provide your bottle.json)

**bottle.yml**

```yml
Arch: win64
Creation_Date: '2021-12-22 01:35:08.264102'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-1.9.2
Environment: Gaming
External_Programs: {}
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
- mono
- dotnet35
- dotnet35sp1
- dotnet40
- dotnet472
- dotnet48
- dotnetcore3
- dotnetcoredesktop3
- vcredist2005
- vcredist2008
- vcredist2010
Latest_Executables: []
NVAPI: dxvk-nvapi-v0.5.1
Name: Games
Parameters:
    aco_compiler: false
    discrete_gpu: true
    dxvk: true
    dxvk_hud: false
    dxvk_nvapi: true
    environment_variables: ''
    fixme_logs: false
    fsr: false
    fsr_level: 5
    gamemode: true
    pulseaudio_latency: true
    sync: esync
    use_runtime: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkd3d: true
Path: Games
Programs: {}
Runner: vaniglia-6.23
State: 0
Uninstallers:
    arial32: false
    courie32: false
    d3dcompiler_43: false
    d3dcompiler_47: false
    d3dx9: false
    dotnet35: true
    dotnet35sp1: true
    dotnet40: Microsoft .NET Framework 4 Extended
    dotnet472: true
    dotnet48: true
    dotnetcore3: true
    dotnetcoredesktop3: true
    mono: true
    msls31: false
    times32: false
    vcredist2005: true
    vcredist2008: true
    vcredist2010: true
Update_Date: '2021-12-22 01:45:49.821115'
VKD3D: vkd3d-v2.4
Versioning: false
Windows: win10
WorkingDir: ''
```
