### ISSUE TITLE
[Request dependency] MDAC28

### ISSUE THREAD

**Issue by philippfreyer** [bottlesdevs/dependencies#114]
**Dependency name**: mdac28

**Official link to the download page (not direct download)** https://web.archive.org/web/20200812031821/https://download.microsoft.com/download/9/a/1/9a1256c9-d301-4fdc-93b9-370c5b2f9827/mdac28sdk.msi

Original: https://download.microsoft.com/download/9/a/1/9a1256c9-d301-4fdc-93b9-370c5b2f9827/mdac28sdk.msi

**Is this dependency compatible with Wine?**
- [ x ] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
They can be links to guides for its implementation or testing or other. Each reference can be useful to maintainers to implement the dependency.

Microsoft page for this:
https://www.microsoft.com/en-us/download/details.aspx?id=21995

Dependency required for installing Enterprise Architect in a bottle:
https://sparxsystems.com/enterprise_architect_user_guide/16.0/getting_started/enterprise_architect_linux.html

Winetricks section:
```

#----------------------------------------------------------------

w_metadata mdac28 dlls \
    title="Microsoft Data Access Components 2.8 sp1" \
    publisher="Microsoft" \
    year="2005" \
    media="download" \
    file1="MDAC_TYP.EXE" \
    installed_file1="${W_COMMONFILES_X86_WIN}/System/ADO/msado27.tlb"

load_mdac28()
{
    w_package_unsupported_win64

    # https://www.microsoft.com/en-us/download/details.aspx?id=5793
    w_download https://web.archive.org/web/20070127061938/https://download.microsoft.com/download/4/a/a/4aafff19-9d21-4d35-ae81-02c48dcbbbff/MDAC_TYP.EXE 157ebae46932cb9047b58aa849ac1885e8cbd2f218810cb83e57613b49c679d6
    load_native_mdac
    w_set_winver nt40
    w_try_cd "${W_CACHE}"/"${W_PACKAGE}"
    w_try "${WINE}" mdac_typ.exe ${W_OPT_UNATTENDED:+/q /C:"setup /qnt"}
    w_set_winver 'default'
}

#----------------------------------------------------------------

```

**Comment by keenanweaver** [comment]
Here's the manifest. That application seems to launch but not sure how to fully verify the mdac28 component is working as intended. It requires the bottle to be set to Windows 98/32-bit. If `set_windows` had all the Windows versions, I could submit an MR for this.

``` yml
Name: mdac28
Description: Microsoft Data Access Components 2.8 SP1
Provider: Microsoft
License: Microsoft EULA
License_url:
Dependencies: []
Steps:
# Set OS to supported version. Win98 or NT40
#- action: set_windows
#  version: win98

- action: override_dll
  bundle:
    - value: odbccp32
      data: native,builtin
    - value: mtxdm
      data: native,builtin
    - value: odbc32
      data: native,builtin
    - value: oledb32
      data: native,builtin

- action: install_exe
  file_name: MDAC_TYP.EXE
  url: https://web.archive.org/web/20070127061938/https://download.microsoft.com/download/4/a/a/4aafff19-9d21-4d35-ae81-02c48dcbbbff/MDAC_TYP.EXE
  file_checksum: 6e914a7391c3b17380ce54fd3a7a133d
  arguments: /q /C:"setup /qnt"
```

![ea](https://user-images.githubusercontent.com/37268985/189946220-3adec70e-9c87-4d07-8001-91df5898111e.png)
