### ISSUE TITLE
[Report] Microsoft .NET Framework 3.5 Crashes

### ISSUE THREAD

**Issue by qogusdn1017** [bottlesdevs/dependencies#14]
**Which dependency?**
e.g. vcredist2019

**Problem type**
- failed to install

bottle.yml
```yaml
Arch: win64
Creation_Date: '2021-12-24 12:19:21.503265'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-1.9.2
Environment: Software
External_Programs: {}
Installed_Dependencies:
- arial32
- times32
- courie32
- dotnet48
- vcredist2013
- vcredist2015
- dotnetcoredesktop3
- dotnet40
Latest_Executables:
-   args: ''
    file: "/home/qogusdn1017/Desktop/\uD55C\uAE00 2020/Install.exe"
    name: Install.exe
-   args: ''
    file: /home/qogusdn1017/Desktop/dotnetfx35.exe
    name: dotnetfx35.exe
-   args: ''
    file: /home/qogusdn1017/Desktop/dotnetfx35.exe
    name: dotnetfx35.exe
-   args: ''
    file: "/home/qogusdn1017/Desktop/\uD55C\uAE00 2020/Install.exe"
    name: Install.exe
-   args: ''
    file: /home/qogusdn1017/Desktop/dotnetfx35.exe
    name: dotnetfx35.exe
-   args: ''
    file: /home/qogusdn1017/Desktop/dotnetfx35.exe
    name: dotnetfx35.exe
-   args: ''
    file: /home/qogusdn1017/Desktop/dotnetfx35.exe
    name: dotnetfx35.exe
NVAPI: dxvk-nvapi-v0.5.1
Name: Hancom Office
Parameters:
    aco_compiler: false
    discrete_gpu: false
    dxvk: true
    dxvk_hud: false
    dxvk_nvapi: false
    environment_variables: ''
    fixme_logs: false
    fsr: false
    fsr_level: 5
    gamemode: false
    pulseaudio_latency: false
    sync: wine
    use_runtime: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkd3d: true
Path: Hancom-Office
Programs: {}
Runner: vaniglia-6.23
State: 0
Uninstallers:
    arial32: false
    courie32: false
    dotnet35: true
    dotnet35sp1: true
    dotnet40: Microsoft .NET Framework 4 Extended
    dotnet48: true
    dotnetcoredesktop3: true
    times32: false
    vcredist2013: true
    vcredist2015: true
Update_Date: '2021-12-24 14:25:48.150645'
VKD3D: vkd3d-v2.4
Versioning: false
Windows: win10
WorkingDir: ''
```

**Describe the problem**
dotnet cannot be installed with this output:
```
024c:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
025c:err:eventlog:ReportEventW L"setup.exe"
025c:err:eventlog:ReportEventW L"9.0.30729.1"
025c:err:eventlog:ReportEventW L"488f1f5c"
025c:err:eventlog:ReportEventW L"sitsetup.dll"
025c:err:eventlog:ReportEventW L"0.0.0.0"
025c:err:eventlog:ReportEventW L"488f1f8f"
025c:err:eventlog:ReportEventW L"0"
025c:err:eventlog:ReportEventW L"00047ef6"
```

and displays a crash message box.
