### ISSUE TITLE
[Report]vc6sp6 doesn't install successfully

### ISSUE THREAD

**Issue by agowa** [bottlesdevs/dependencies#199]
**Which dependency?**
e.g. vcredist6sp6

**Problem type**
- failed to install (provide your bottle.json)

**Describe the problem**
Appears to install just fine, but dlls aren't present and applications fail to start.
When trying to manually go through the steps in teh dependencies install file it can be seen that probably this https://github.com/bottlesdevs/dependencies/blob/main/Essentials/vcredist6sp6.yml#L20 step fails, as when run with "/G C:\log.txt" it generates a logfile with a terminating error (see below).

```
************************************************************
Microsoft Setup Log File Opened 09/26/23 00:04:23
Version number: 3.01.0.1918
Running under Windows NT.
[00:04:23  Start of Pass: 0]
Command Line: /T sp698ent.stf /n "" /o "" /S C:\VS6SP6\ /G C:\log.txt /b1
[00:04:23  Start of Pass: 1]
Floppy mode
Processing the header information of the file: Z:\~MSSETUP.T\tmp.t\sp698ent.stf
************************************************************
  Application name: Visual Studio 6.0 Service Pack 6
  Application version: 6.0.0.0.0311 (1033)
  Frame caption: Visual Studio 6.0 Service Pack 6 Setup
  Dialog caption base: Visual Studio 6.0 Service Pack 6
  Modules: ThunderRT5Main,Microsoft Visual Basic,ThunderRTMain,Microsoft VB Runt
ime,RaidClass,Microsoft Raid,MSVCED50,Microsoft Developer Studio,wndclass_desked
_gsk,Microsoft Development Environment
  Modules2: Fox_4000001,Microsoft Visual FoxPro, graph, MS Graph, ed, MS Draw, m
sinfo, MS Info,odbcad32,ODBC administrator,odbcjt32, ODBC Driver, !Microsoft Exc
hange!, Microsoft Exchange
  Modules3: OMain,Microsoft Access, msaccess,MS Access,msarn110,MS Access Runtim
e,msarn200,MS Access Runtime,MS:SCC:REFRESH,Microsoft Visual SourceSafe,MSOffice
WClass,Microsoft Office Manager
  Modules4: VFP66400000,Microsoft Visual FoxPro,valecstart,Visual Studio Analyze
r Server
  MSApps mode: local
  INF file name: sp698ent.inf
[00:04:26  Start of Pass: 2]
[00:04:26  Start of Pass: 3]
[00:04:26  Start of Pass: 4]
[00:04:30  Start of Pass: 5]
[00:04:30  Start of Pass: 6]
Do not ship.
Error message to log
function that detects what VS products are installed in what language unable to 
function.
Microsoft Setup Log File Closed 09/26/23 00:04:36

```

```yml
Arch: win64
CompatData: ''
Creation_Date: '2023-09-25 23:43:11.476266'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-2.2
Environment: Application
Environment_Variables: {}
External_Programs: {}
Installed_Dependencies:
- arial32
- times32
- courie32
- mfc40
- vcredist6sp6
- vcredist2005
- vcredist6
Language: sys
LatencyFleX: latencyflex-v0.1.1
NVAPI: dxvk-nvapi-v0.6.3
Name: App001
Parameters:
    custom_dpi: 96
    decorated: true
    discrete_gpu: false
    dxvk: true
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_quality_mode: none
    fsr_sharpening_strength: 2
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    latencyflex: false
    mangohud: false
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: false
    renderer: gl
    sandbox: false
    sync: wine
    take_focus: false
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    versioning_automatic: false
    versioning_compression: false
    versioning_exclusion_patterns: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkbasalt: false
    vkd3d: true
    vmtouch: false
    vmtouch_cache_cwd: false
Path: App001
Runner: soda-7.0-9
RunnerPath: ''
Sandbox:
    share_net: false
    share_sound: false
State: 0
Uninstallers: {}
Update_Date: '2023-09-26 00:07:09.198269'
VKD3D: vkd3d-proton-2.9
Versioning: false
Versioning_Exclusion_Patterns: []
Windows: win10
WorkingDir: ''
data: {}
run_in_terminal: true
session_arguments: ''
```
