### ISSUE TITLE
[Report] dotnet35 fails with error 1603

### ISSUE THREAD

**Issue by chabad360** [bottlesdevs/dependencies#21]
**Which dependency?**
`dotnet35`

**Problem type**
- failed to install

`bottle.yml`:
```yml
Arch: win64
Creation_Date: '2022-01-17 16:07:23.975473'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-1.9.2
Environment: Custom
Environment_Variables: {}
External_Programs: {}
Installed_Dependencies:
- dotnet35
Latest_Executables: []
NVAPI: dxvk-nvapi-v0.4
Name: dotnet35
Parameters:
    aco_compiler: false
    discrete_gpu: false
    dxvk: false
    dxvk_hud: false
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_level: 5
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    pulseaudio_latency: false
    sync: wine
    use_runtime: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkd3d: false
Path: dotnet35
Programs: {}
Runner: sys-wine-7.0-rc5
State: 0
Uninstallers:
    dotnet35: true
Update_Date: '2022-01-17 16:12:20.192675'
VKD3D: vkd3d-v2.4
Versioning: false
Windows: winxp
WorkingDir: ''
```

> Note: this is the state immediately after the error

**Describe the problem**
Attempting to install `dotnet35` fails with error 1603:

```
[01/17/22,16:11:31] Microsoft .NET Framework 2.0a x64: [2] Error: Installation failed for component Microsoft .NET Framework 2.0a x64. MSI returned error code 1603
[01/17/22,16:11:36] WapUI: [2] DepCheck indicates Microsoft .NET Framework 2.0a x64 is not installed.
```
