### ISSUE TITLE
[Request dependency] PhysX

### ISSUE THREAD

**Issue by Nocifer** [bottlesdevs/dependencies#25]
**Dependency name**
PhysX

**Official link to the download page:**
https://www.nvidia.com/en-us/drivers/physx/physx-9-19-0218-driver/

**Is this dependency compatible with Wine?**
Yes, at least when installed manually or via Winetricks

I've created a .yml instructions file but AFAIK I have no way to test if it works properly, here it is:

```
Name: physx
Description: NVIDIA PhysX System
Provider: Nvidia
License:  NVIDIA GeForce Software
License_url: https://www.nvidia.com/en-us/drivers/geforce-license/?type=GeForce
Uninstaller: NVIDIA PhysX System
Steps:
- action: install_exe
  file_name: PhysX-9.19.0218-SystemSoftware.exe
  url: https://us.download.nvidia.com/Windows/9.19.0218/PhysX-9.19.0218-SystemSoftware.exe
  rename: PhysX_9.19.0218.exe
  file_checksum: 3b56abd0bc89090b6d6ceeaf2b5d27577b7b76b6
```

This is needed for some games that without it fail to launch but otherwise work perfectly fine, e.g. for Dragon Age - Origins.

**Comment by mirkobrombin** [comment]
Hi, you can test this using a local repository if you want:
1. close https://github.com/bottlesdevs/dependencies on your pc
2. make your changes
3. start bottles with: `LOCAL_DEPENDENCIES=/path/to/dependencies flatpak run com.usebottles.bottles`

**Comment by Nocifer** [comment]
Hi again; is there a way to pass flags to the install function? Physx setup needs to be run with an '/s' flag (for 'silent') in order to perform the install without asking for user input.

Also, please see #24 again for some new info on that front.

**Comment by mirkobrombin** [comment]
> Hi again; is there a way to pass flags to the install function? Physx setup needs to be run with an '/s' flag (for 'silent') in order to perform the install without asking for user input.

Yup: https://github.com/bottlesdevs/maintainers-docs/blob/main/dependencies/structure/Actions.md#install_exe-or-install_msi

**Comment by Nocifer** [comment]
For some reason I can't get the official url to work, the setup file is not being fetched even though I tested with wget and curl and they both managed to download the file successfully.

I ended up using a different, third-party url to test and it turns out this works properly: installing with the /s flag is successful, the installed files are present at their expected locations, the game which requires Physx launches without a hitch, and removing the dependency successfully launches the PhysX uninstaller and allows me to uninstall the runtime.

Could you please test it on your end and see if you can make it work with the official url? The commented out lines are for the third-party file I used for my tests (the checksum is also different because the file is a different, older PhysX version).

```
Name: physx
Description: NVIDIA PhysX System 9.19.0218
Provider: Nvidia
License: NVIDIA GeForce Software
License_url: https://www.nvidia.com/en-us/drivers/geforce-license/?type=GeForce
Uninstaller: NVIDIA PhysX System
Steps:
- action: install_exe
  file_name: PhysX-9.19.0218-SystemSoftware.exe
  url: https://uk.download.nvidia.com/Windows/9.19.0218/PhysX-9.19.0218-SystemSoftware.exe
  #url: https://www.lo4d.com/get-file/nvidia-physx/765ac4411641c667a141c32de0433138/
  rename: physx.exe
  file_checksum: a7b900bec0b7b386dfd18ad22c9ed411
  #file_checksum: abbe223de055097b47e0da0ba88b4beb
  arguments: /s
```
