### ISSUE TITLE
[Report] dotnet472 fails to install, tries to install 4.6 instead

### ISSUE THREAD

**Issue by killarny** [bottlesdevs/dependencies#263]
**Which dependency?**
dotnet472

**Problem type**
Fails to install.

My `bottle.yml` file:

```yaml
Arch: win64
CompatData: ''
Creation_Date: '2024-10-21 20:46:24.037402'
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-2.3
Environment: Application
Environment_Variables: {}
External_Programs: {}
Installed_Dependencies:
- arial32
- times32
- courie32
- mono
- gecko
- dotnet40
- dotnet45
Language: sys
LatencyFleX: latencyflex-v0.1.1
NVAPI: dxvk-nvapi-v0.6.4
Name: Test
Parameters:
    custom_dpi: 96
    decorated: true
    discrete_gpu: false
    dxvk: true
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_quality_mode: none
    fsr_sharpening_strength: 2
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    latencyflex: false
    mangohud: false
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: false
    renderer: gl
    sandbox: false
    sync: wine
    take_focus: false
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    versioning_automatic: false
    versioning_compression: false
    versioning_exclusion_patterns: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkbasalt: false
    vkd3d: true
    vmtouch: false
    vmtouch_cache_cwd: false
Path: Test
Runner: soda-9.0-1
RunnerPath: ''
Sandbox:
    share_net: false
    share_sound: false
State: 0
Uninstallers: {}
Update_Date: '2024-10-21 20:48:58.216953'
VKD3D: vkd3d-proton-2.11.1
Versioning: false
Versioning_Exclusion_Patterns: []
Windows: win10
WorkingDir: ''
data: {}
run_in_terminal: false
session_arguments: ''
```

**Describe the problem**
An error is displayed that says ".NET Framework 4.6 or a later update is already installed on this computer.", but the installer should be installing .NET Framework 4.7.

![image](https://github.com/user-attachments/assets/cd625a2e-570b-4917-9326-8a6bab87b2f6)

As you can see, dotnet472 was selected (note the spinner) and I have not actually installed any of the dotnet46* packages either.

According to the bottle.yml file, only dotnet40 and dotnet45 should be installed already (though I don't know where to look to verify that).
