### ISSUE TITLE
"Bucket" dependencies for service pack and archives

### ISSUE THREAD

**Issue by mirkobrombin** [bottlesdevs/dependencies#4]
Some dependencies need to extract dependencies from service packs and archives. We can imagine these archives as buckets from which to take one or more files.

So with the oncoming "nested dependencies" (where one dependency can declare its dependencies and then install them first), we can migrate them to their own manifest file. I think it is good to not put these inside the index.yml/testing.yml files, so the user cannot install these like other dependencies, so can be installed only by other dependencies.

Examples:

gdiplus.yml
```yaml
Name: gdiplus
Description: Microsoft GDI+ (Graphics Device Interface)
Provider: Microsoft
License: Microsoft EULA
License_url: https://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm
Dependencies: 
 - windows6.1-kb976932-x86
 - windows6.1-kb976932-x64

- action: copy_cab_dll
  file_name: gdiplus.dll
  url: temp/windows6.1-kb976932-x86/x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_72d18a4386696c80
  dest: windows/system32/gdiplus.dll
  
- action: copy_cab_dll
  file_name: gdiplus.dll
  url: temp/windows6.1-kb976932-x64/amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_2b24536c71ed437a
  dest: windows/syswow64/gdiplus.dll

- action: override_dll
  dll: gdiplus
  type: native,builtin
```

windows6.1-kb976932-x86.yml:
```yaml
Name: windows6.1-kb976932-x86
Description: Windows 6.1 kb976932 32 Bit
Provider: Microsoft
License: Microsoft EULA
License_url: https://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm
Steps:
- action: cab_extract
  file_name: windows6.1-kb976932-x86_c3516bc5c9e69fee6d9ac4f981f5b95977a8a2fa.exe
  url:  http://download.windowsupdate.com/msdownload/update/software/svpk/2011/02/windows6.1-kb976932-x86_c3516bc5c9e69fee6d9ac4f981f5b95977a8a2fa.exe
  rename: windows6.1-kb976932-x86.exe
  file_checksum: 4bf28fc00d86c936c89e2d91ef46758b
```

windows6.1-kb976932-x64.yml.
```yaml
Name: windows6.1-kb976932-x64
Description: Windows 6.1 kb976932 64 Bit
Provider: Microsoft
License: Microsoft EULA
License_url: https://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm
Steps:
- action: cab_extract
  file_name: windows6.1-kb976932-x64_74865ef2562006e51d7f9333b4a8d45b7a749dab.exe
  url:  http://download.windowsupdate.com/msdownload/update/software/svpk/2011/02/windows6.1-kb976932-x64_74865ef2562006e51d7f9333b4a8d45b7a749dab.exe
  rename: windows6.1-kb976932-x64.exe
  file_checksum: 28d3932f714bf71d78e75d36aa2e0fb8
```
