### ISSUE TITLE
i18n enable translation of category and description

### ISSUE THREAD

**Issue by ovari** [bottlesdevs/dependencies#6]
Please enable category and description to be translatable.

**Comment by mirkobrombin** [comment]
There are multiple way to do this but in every case we are going to hardly increase the work to the maintainers.

#### Using translations in manifests
Using this method, all the translations should be located in the manifest using the locale as suffic (en_US, it_IT..):

```yaml
Name: d3dx9

Description_en_US: Microsoft d3dx9 DLLs from DirectX 9 redistributable
Description_it_IT: Microsoft d3dx9 DLLs da DirectX 9 ridistribuibile

Provider: Microsoft
License: Microsoft EULA
License_url: https://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm
Dependencies: []
Steps:
- action: cab_extract
  file_name: directx_Jun2010_redist.exe
  url: ...
```

this can be a problem with long manifests:
- https://github.com/bottlesdevs/dependencies/blob/main/Essentials/d3dx9.yml
- https://github.com/bottlesdevs/dependencies/blob/main/Fonts/allfonts.yml

#### Using translation files
In this case we move all the strings from the manifest:

```yaml
Name: d3dx9
Provider: Microsoft
License: Microsoft EULA
License_url: https://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm
Dependencies: []
Steps:
- action: cab_extract
  file_name: directx_Jun2010_redist.exe
  url: ...
```

to a `/Translations` path, e.g. `/Translations/d3dx9.yml`:

```yaml
Description_en_US: Microsoft d3dx9 DLLs from DirectX 9 redistributable
Description_it_IT: Microsoft d3dx9 DLLs da DirectX 9 ridistribuibile
```

the problem here is that we increase the number of requests to the repository because now we make a single call to the index file. With external translations, we have to make a call to the index file and then one for each dependency to get its own translations.

#### Only translate categories
Categories are folders in this repository. These are used by the index file to figure out where a dependency is placed.

To translate these we can go to a model based on translation keys, then the index file:

```yaml
# Redist
vcredist2013:
  Description: Microsoft Visual C++ Redistributable (2013) 12.0
  Category: ESSENTIALS
vcreditst2015:
  Description: Microsoft Visual C++ Redistributable (2015)
  Category: ESSENTIALS
vcredist2019:
  Description: Microsoft Visual C++ Redistributable (2015-2019) 14.28.29325
  Category: ESSENTIALS

...

# fonts
allfonts:
  Description: All Microsoft and Adobe essential fonts
  Category: FONTS
...
```

renaming the directories to fit the new standard:
- `/Essentials` -> `/ESSENTIALS`
- `/Fonts` -> `/FONTS`

creating the new `/Translations` path, then create a translation file for each category, e.g. for `/translations/ESSENTIALS.yml`:

```yaml
en_US: Essentials
it_IT: Essenziali
...
```

Unfortunately, as before, it is not possible because this would increase the number of calls (even if less than the previous one).

There are plans to add [cache support in Bottles](https://github.com/bottlesdevs/Bottles/issues/439). In this way it is possible to download a local copy of the repository and therefore also the translations. Currently there is no timeline for such feature.
