### ISSUE TITLE
[Request dependency] Windows media player 11 (WMP11)

### ISSUE THREAD

**Issue by Midou36O** [bottlesdevs/dependencies#93]
**Dependency name**: wmp11/ Windows Media Player 11

**Official link to the download page (not direct download)** https://www.catalog.update.microsoft.com/Search.aspx?q=kb976932

**Is this dependency compatible with Wine?**
- [X] Yes
- [ ] Yes, but need tweaks
- [ ] No
- [ ] I have not tested

**Useful links**
¯\\\_(ツ)_/¯

Note (off-topic):
**Since bottle does not support winetricks, the dependencies that are available on winetricks are not installable that easily. And such should be re-added into the dependencies list**

**Comment by xrishox** [comment]
would love to see windows media player of some form or another be added to bottles. there are a lot of random things that tend to depend on it. if wmp11 is too difficult to get up and running perhaps wmp10 or wmp9 would be easier?

**Comment by lemonzest79** [comment]
I would like this also, had two games that require WMP of some kinda for wmv playback, one game even crashes on start because it can not show its intro video (BlazBlue Calamity something) and King of Fighters XIII Needs it to shows videos in game (screen flashes green and the video does not play)

**Comment by keenanweaver** [comment]
Here's what I think the manifests for WMP would be. It'd require some additional functions to be made (or migrated) in Bottles. It may be possible with current Bottles functionality, but basing it off Winetricks it's currently not possible.

``` yaml
Name: wmp9
Description: Microsoft Windows Media Player 9 and codecs
Provider: Microsoft
License: Microsoft EULA
License_url:
Dependencies: []
Steps:
- action: set_windows
  version: winxp

# Remove files (If Bottles' Installers 'run_script' function was implemented for dependencies)
#- action: run_script
#  script: |
#  rm -f !bottle_drive/Program\ Files\ (x86)/Windows\ Media\ Player/wmplayer.exe !bottle_drive/Windows/syswow64/wmp.dll

- action: override_dll
  bundle:
    - value: l3codeca.acm
      data: native
    - value: wmp
      data: native
    - value: wmplayer.exe
      data: native
    - value: wmvcore
      data: native

- action: cab_extract
  file_name: MPSetup.exe
  url: https://web.archive.org/web/20180404022333if_/download.microsoft.com/download/1/b/c/1bc0b1a3-c839-4b36-8f3c-19847ba09299/MPSetup.exe
  file_checksum: e919c4e0050b32aebe83a5d2eb613dd4
  dest: temp/MPSetup/

# Command to edit setup_wm.exe file in place (If Bottles' Installers 'run_script' function was implemented for dependencies)
# sed -i 's/IsWow64Process/IsNow64Process/' setup_wm.exe
#- action: run_script
#  script: |
#  sed -i 's/IsWow64Process/IsNow64Process/' setup_wm.exe

- action: install_exe
  file_name: setup_wm.exe
  url: MPSetup/
  file_checksum: 6560a06288752e36a5ccda0b9d115e31
  arguments: /Quiet

- action: install_exe
  file_name: WM9Codecs9x.exe
  url: https://archive.org/download/WM9Codecs/WM9Codecs9x.exe
  file_checksum: 6560a06288752e36a5ccda0b9d115e31
  arguments: /q
```

``` yaml
Name: wmp10
Description: Microsoft Windows Media Player 10
Provider: Microsoft
License: Microsoft EULA
License_url:
Dependencies: []
Steps:
- action: set_windows
  version: winxp

# Remove files (If Bottles' Installers 'run_script' function was implemented for dependencies)
#- action: run_script
#  script: |
#  rm -f !bottle_drive/Windows/syswow64/wmp.dll !bottle_drive/Windows/syswow64/wmvcore.dll

- action: override_dll
  bundle:
    - value: l3codeca.acm
      data: native
    - value: wmp
      data: native
    - value: wmplayer.exe
      data: native
    - value: wmvcore
      data: native

- action: install_exe
  file_name: MP10Setup.exe
  url: https://web.archive.org/web/20200803205216/https://download.microsoft.com/download/1/2/a/12a31f29-2fa9-4f50-b95d-e45ef7013f87/MP10Setup.exe
  file_checksum: e57645c5ab34485d56d019aaa17c3150
  arguments: /q:A /c:"setup_wm.exe /Q /R:N"

# Remove registry entries (If Bottles' Installers 'run_winecommand' function was implemented for dependencies)
#- action: wine_winecommand
#  commands:
#    - command: regedit
#      arguments: /D "HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\Cdr4_2K"
#      minimal: true
#    - command: regedit
#      arguments: /D "HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\Cdralw2k"
#      minimal: true

- action: install_exe
  file_name: WM9Codecs9x.exe
  url: https://archive.org/download/WM9Codecs/WM9Codecs9x.exe
  file_checksum: 6560a06288752e36a5ccda0b9d115e31
  arguments: /q
```
``` yaml
Name: wmp11
Description: Microsoft Windows Media Player 11
Provider: Microsoft
License: Microsoft EULA
License_url:
Dependencies: []
Steps:
- action: set_windows
  version: winxp

# Remove files (If Bottles' Installers 'run_script' function was implemented for dependencies)
#- action: run_script
#  script: |
#  rm -f !bottle_drive/Windows/syswow64/wmvcore.dll !bottle_drive/Windows/syswow64/mfplat.dll !bottle_drive/Windows/syswow64/wmasf.dll !bottle_drive/Windows/syswow64/wmpnssci.dll
#  rm -f !bottle_drive/Windows/system32/wmvcore.dll !bottle_drive/Windows/system32/mfplat.dll !bottle_drive/Windows/system32/wmasf.dll !bottle_drive/Windows/system32/wmpnssci.dll

- action: override_dll
  bundle:
    - value: l3codeca.acm
      data: native
    - value: mfplat
      data: native
    - value: wmasf
      data: native
    - value: wmp
      data: native
    - value: wmplayer.exe
      data: native
    - value: wmpnssci
      data: native
    - value: wmvcore
      data: native

# 32-bit prefix only
#- action: install_exe
#  file_name: wmp11-windowsxp-x86-enu.exe
#  url: https://web.archive.org/web/20170628063001/http://download.microsoft.com/download/0/9/5/0953e553-3bb6-44b1-8973-106f1b7e5049/wmp11-windowsxp-x86-enu.exe
#  file_checksum: 5a8299fec0ed0f7b6f50e1dabd76ff93
#  arguments: /q:A /c:"setup_wm.exe /Q /R:N"

# 64-bit prefix only
- action: install_exe
  file_name: wmp11-windowsxp-x64-enu.exe
  url: https://web.archive.org/web/20190512112704/https://download.microsoft.com/download/3/0/8/3080C52C-2517-43DE-BDB4-B7EAFD88F084/wmp11-windowsxp-x64-enu.exe
  file_checksum: 8bc7f3cd5f20fd04a607360bbeda46cf
  arguments: /q:A /c:"setup_wm.exe /Q /R:N"

# Remove registry entries (If Bottles' Installers 'run_winecommand' function was implemented for dependencies)
#- action: wine_winecommand
#  commands:
#    - command: regedit
#      arguments: /D "HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\Cdr4_2K"
#      minimal: true
#    - command: regedit
#      arguments: /D "HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\Cdralw2k"
#      minimal: true
```
